language: python
python: '2.7'
install:
  pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
    - GCE_CREDENTIALS_FILE="$(pwd)/travis.json"
  global:
  - secure: "aLUrMkEoybPaUy6ishb4cBv8ySr2z0hSrvbVecfD2Z2dG5kAYPkFCyQyNbmstUWItbATGBezJgKs66wZKmiJ5YLgqtuy5rqbeQ+YnR68UGWBKOIdvHMVClHzgKLQO8n4sw8ItCmvelPIELfcuo59CAan/3mygP7FqScDiBiWTYZL2a9N25hm00SZngXPlhPz5AazQ/nL4OiwgLM8ep2X+PGVugcYdnrVpxSfwqbHelKO0d7EvtBBTrpbcAaX6DFDBDmKvmuz5hZ/3e9FKb7ASgoEuVJHo6lfK6P4atLwR+XQzGWqH2k1dMvEHWZVDMQ8xrE/rcsSqTWmvSl71XInitscnAV3MT1x8bhiM9tIX/v1Hw5dSv/maojkAByEqTVwVhCKM5S4YM8xHjO1uchBpis47NBf4PPcDzcDnCc9UVZyzMP6/li8ynaIEvInyGTqJ7HFhVWLurHKT7jLggv7jWtxMHwEqlVXaJNdgdWwqd2Opqb9WTGbcs9fWXRRv7EH6itwHPiin70mXYyQI7PN+2JjsgrIn7BcTSFZvj7hWjqwMb+a6NGq+yHsVB4Y4K3d3B+jMkQCAUb+AvIArVJaI6dbLVLoh0y7GQ+fWP25w1TT9Q7cMnia20UjnL5QZD2sNQtDi1WO0AvJkmJNai97Ve1p/t6OV2beyDOQlP7oelQ="
  - secure: "P78DXRY0me0dY+HcNors9qxaxLf9ycnPXLe2CB9KIiF8IUCwbGLPYMYFxwrXit25VZEpsSFY0O+GOKl7WpT8eD/lJ7MWWzKen2ZlHNRz7oiDHQyc4EbwHUhsM5mOv5bJt18ZvxtPsIKVGEDiYH+IBJAIaeWYBw6lvJfc+Fe4z3kdrpAu/v7MwIrnNPUSC2O+lX4R5nnrHqHQSJ/9SlGCU7vkknaZVML4tiMVKdE67wjrpNqTr5+jtdMchxysejX3CvQ2Hx6t8fzr2v8k/biWP9Si84WRBt9TnmkFg3DzKuKVbdyWh/NNMMlGyQwLowpu0WySgwYljViFv/aulbWHEmks+sgEihCyjbBKrAmxZ11zGmN+c7qazQldFARgpcCBBZzR8fccSSm3kg5Y63DtGOWz5xOR24MWB5v16e/k5nSDnyvSly7tzzcDrR5UpejZt3NZUsxgqTaQJP3q2Mt1OOVMfeLb6ZwJ8hn70KAYM5y/B9WqpG9PZpT46ndzDipoFAvpTG0Y9ZZAQvWGIEFDL8Aw/8qACR5OG6oIXou6mDoBeRWyZX5vzPEB+gKLbhC5QYXVUadkbKDwCBObs4pbKY4SGgs+xRBbkxDo6pifxaB4yclxgGXBZensGylJL4TGCfFa9+xQ+9ktpVSX1lyYHNiZntkdU3zjNebDFzAYLDM="
  - secure: "lkB1aaGgUbUYcUt1vTSxsRrtx6M2krGZ/bGufX4IKy0APZC3xpubMyqv9Nj9lg/+5YAvTk3JO/KdnjK2jEY1nhhQq76Kf/6qDP6Vqd6tMUqQ95JgRzifpgQzxtcnP2xaBzhuH8zdQo+VkTD5qOrBXWUU3BwfSujbQCfeqxaxEjcsFx1C33aT5BE3faWZjZt1aux6PTANJV93YWAB5bZu/aUWik5Jy1d8LDRWgMQ4avooZUhv3t8z6K42q2K1DNOevnWisoUzC0AwtkDYt34tepv4B7XqIuSYzS+ALeTe8xdN4zZXa72CSpEOUNUZ8hS1if7+EP0qIg3+brLuCcQN6ZdyXI6Uko6UTanFlsXUUj8L5gW5YcrvZh6Q+qq6tvsCV/Z/wqdNnasE6sLO6bPnHz4jqpJg5cuJ269iTIGm6SucfmQkuM3GJsB4FXva6Zmz8VL7NvQsFkPY6QrKmHN/e/JPAq9Siw0FjYI2OwBgS4HD+hNP1/zM1uZ4RAEXcxvPYr93PE4/najwnoUDmZaBerntmPaZPCdt2o9ZqLhoQYw60sz4u4mtfabHY9oIqYaBTZ6mQ+MK4lb28XMIEuLBAshI5+BXJmVeW3V2PnnKuhWhG3a1fCzJe2qQ7yoUCp190rrv9ZAifJVut3lmQ0Y677DrYpfD/Cb2oCKdzT7X6NY="
before_install:
#- openssl aes-256-cbc -K $encrypted_21e31a4d3869_key -iv $encrypted_21e31a4d3869_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
script:
  - molecule create
  - molecule converge
  - molecule verify
after_script:
  - molecule destroy
